/**
 * Constants
 * Application-wide constants
 */

const USER_ROLES = {
  DONOR: 'DONOR',
  NGO: 'NGO',
  ADMIN: 'ADMIN',
};

const NGO_VERIFICATION_STATUS = {
  PENDING: 'PENDING',
  VERIFIED: 'VERIFIED',
  REJECTED: 'REJECTED',
};

const CAMPAIGN_STATUS = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED',
  FAILED: 'FAILED',
  CLOSED: 'CLOSED',
};

const CAMPAIGN_CATEGORY = {
  HEALTH: 'HEALTH',
  EDUCATION: 'EDUCATION',
  DISASTER_RELIEF: 'DISASTER_RELIEF',
  ENVIRONMENT: 'ENVIRONMENT',
  POVERTY: 'POVERTY',
  OTHER: 'OTHER',
};

const DONATION_STATUS = {
  PENDING: 'PENDING',
  CONFIRMED: 'CONFIRMED',
  FAILED: 'FAILED',
};

const BLOCKCHAIN_NETWORK = {
  ETHEREUM: 'ETHEREUM',
  POLYGON: 'POLYGON',
  BINANCE: 'BINANCE',
};

const PAYMENT_METHOD = {
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  CRYPTO: 'CRYPTO',
  PAYPAL: 'PAYPAL',
};

const CURRENCY = {
  USD: 'USD',
  EUR: 'EUR',
  GBP: 'GBP',
  INR: 'INR',
};

module.exports = {
  USER_ROLES,
  NGO_VERIFICATION_STATUS,
  CAMPAIGN_STATUS,
  CAMPAIGN_CATEGORY,
  DONATION_STATUS,
  BLOCKCHAIN_NETWORK,
  PAYMENT_METHOD,
  CURRENCY,
};
